---
title: "testcase"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("./BartImputeCox_0.1.0.tar.gz")
library(BartImputeCox)
library(mice)
library(survival)
library(parallel)
library(rje)
options(warn = -1)
```

```{r}
true_beta = c(0.3, -0.2, 0.5)
X = test_data(1234, n = 500, mis = 0.2, method = "MCAR")
T = X$observe
C = X$status
X = X[, -c(1, 2)]

# BART method
covariate_types = c(1, 2, 1)
missing_covariate_start = 1
dataset = as.matrix(X)
result = CBI(T, C, dataset, covariate_types, missing_covariate_start, num_iterations = 6000,burn_in = 2000)
beta = result$beta
estimate = colMeans(beta)
CI = apply(beta, 2, quantile, probs = c(0.025,0.975))
square_error = (true_beta - estimate)^2


# MICE method
imp = mice(X, m = 5, method = c("pmm", "logreg", "pmm"), seed = 1234)
fit = with(imp, coxph(Surv(T, C) ~ x1 + x2 + x3))
mod = summary(pool(fit))
estimate_mice = mod$estimate
CI_mice = cbind(estimate - 1.96 * mod$std.error, estimate + 1.96 * mod$std.error)
square_error_mice = (true_beta - estimate_mice)^2


# Remove all the data
mod = coxph(Surv(T, C) ~ X[,1] + X[,2] + X[,3])
estimate_cox = coef(mod)
CI_cox = confint(mod)
square_error_cox = (true_beta - estimate_cox)^2


rbind(estimate, estimate_mice, estimate_cox)
rbind(square_error, square_error_mice, square_error_cox)
CI_all = cbind(CI, t(CI_mice), t(CI_cox))
colnames(CI_all) = c("CBI_beta1", "CBI_beta2", "CBI_beta3",
                     "MICE_beta1", "MICE_beta2", "MICE_beta3",
                     "Cox_beta1", "Cox_beta2", "Cox_beta3")
CI_all
```

