# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cCBI <- function(T, C, X, covariate_types, missing_matrix, time, num_iterations, burn_in, beta, h0, beta_mean, beta_variances, h0_prior_shape, h0_prior_rate, m, numcut, alpha, mybeta, nu, lambda, proposal_stddev_beta, proposal_stddev_h0, proposal_stddev_X, missing_covariate_start) {
    .Call(`_BartImputeCox_cCBI`, T, C, X, covariate_types, missing_matrix, time, num_iterations, burn_in, beta, h0, beta_mean, beta_variances, h0_prior_shape, h0_prior_rate, m, numcut, alpha, mybeta, nu, lambda, proposal_stddev_beta, proposal_stddev_h0, proposal_stddev_X, missing_covariate_start)
}

compute_cox_likelihood <- function(T, C, X, beta, h0, time) {
    .Call(`_BartImputeCox_compute_cox_likelihood`, T, C, X, beta, h0, time)
}

GammaLikelihood <- function(x, shape, rate) {
    .Call(`_BartImputeCox_GammaLikelihood`, x, shape, rate)
}

NormalLikelihood <- function(x, mean, stddev) {
    .Call(`_BartImputeCox_NormalLikelihood`, x, mean, stddev)
}

initialize_and_predict <- function(type, x_train, H0, y_train, x_test, H0_test, m, numcut, mybeta, alpha, tau, nu, lambda) {
    .Call(`_BartImputeCox_initialize_and_predict`, type, x_train, H0, y_train, x_test, H0_test, m, numcut, mybeta, alpha, tau, nu, lambda)
}

initialize_update_and_predict <- function(type, x_train, H0, y_train, x_test, H0_test, m, numcut, mybeta, alpha, tau, nu, lambda) {
    .Call(`_BartImputeCox_initialize_update_and_predict`, type, x_train, H0, y_train, x_test, H0_test, m, numcut, mybeta, alpha, tau, nu, lambda)
}

mh_beta <- function(current_beta, mean, variances, T, C, X, h0, time, proposal_stddev) {
    .Call(`_BartImputeCox_mh_beta`, current_beta, mean, variances, T, C, X, h0, time, proposal_stddev)
}

